export const CONTACTS_GET_REQUEST = "CONTACTS_GET_REQUEST";
export const CONTACTS_GET_SUCCESS = "CONTACTS_GET_SUCCESS";
export const CONTACTS_GET_FAILURE = "CONTACTS_GET_FAILURE";

export const CONTACTS_POST_REQUEST = "CONTACTS_POST_REQUEST";
export const CONTACTS_POST_SUCCESS = "CONTACTS_POST_SUCCESS";
export const CONTACTS_POST_FAILURE = "CONTACTS_POST_FAILURE";